### ISSUE TITLE
IpAllocationPolicy does not allow subnet and CIDR autocreation

### ISSUE THREAD

**Issue by Synehan** [GoogleCloudPlatform/k8s-config-connector#133]
**Describe the bug**
ContainerCluster does not provide a way to activate the use of Ip Aliases anymore without providing Service CIDR block and Cluster CIDR block.

API describes the following resources https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#ipallocationpolicy which are not available anymore in KCC ContainerCluster CRD https://cloud.google.com/config-connector/docs/reference/resources#custom_resource_definition_properties_50

The resources give the following status:

```
'Update call failed: error applying desired state: googleapi: Error 400:
      Alias IP addresses are required for private cluster, please make sure you enable
      alias IPs when creating a cluster., badRequest'
```
Providing an empty value is not possible for the resources:

- spec.ipAllocationPolicy
- spec.ipAllocationPolicy.clusterIpv4CidrBlock
- spec.ipAllocationPolicy.servicesIpv4CidrBlock

**ConfigConnector Version**
1.6.0

**To Reproduce**
Create a private cluster with KCC 

*YAML snippets:*
```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: int-test-cluster
  namespace: cnrm-dev-config
spec:
  addonsConfig:
    cloudrunConfig:
      disabled: true
    horizontalPodAutoscaling:
      disabled: true
    httpLoadBalancing:
      disabled: false
    istioConfig:
      auth: AUTH_MUTUAL_TLS
      disabled: true
    networkPolicyConfig:
      disabled: false
  description: GKE Cluster int-test-cluster
  enableIntranodeVisibility: false
  enableKubernetesAlpha: false
  enableShieldedNodes: false
  enableTpu: false
  initialNodeCount: 1
  location: europe-west1
  loggingService: logging.googleapis.com/kubernetes
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "01:00"
  minMasterVersion: 1.15.9-gke.24
  monitoringService: monitoring.googleapis.com/kubernetes
  networkPolicy:
    enabled: true
    provider: CALICO
  networkRef:
    name: test-cc
  podSecurityPolicyConfig:
    enabled: false
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.2.0/28
  releaseChannel:
    channel: regular
  subnetworkRef:
    name: toto
  verticalPodAutoscaling:
    enabled: false
```

**Expected behavior**
IP Allocation Policies provides the same fields as the API.

**Comment by xiaobaitusi** [comment]
Hi @Synehan, correct me if I'm wrong on this. You intention is to set spec.ipAllocationPolicy.useIpAliases "true" without specifically specifying spec.ipAllocationPolicy.clusterIpv4CidrBlock
spec.ipAllocationPolicy.servicesIpv4CidrBlock but using sever-generated ranges.

Currently the problem is that if you want to enable ip Aliases, you have to provide values for spec.ipAllocationPolicy.clusterIpv4CidrBlock anbd spec.ipAllocationPolicy.servicesIpv4CidrBlock.

**Comment by Synehan** [comment]
Hi @xiaobaitusi, yes exactly

**Comment by jcanseco** [comment]
Hi @Synehan. Yes you are right, the `ipAllocationPolicy.useIpAliases` field of the Cluster REST resource is not (and was never) exposed in the `ContainerCluster` CRD. This appears to be intentional, since you need to specify at least two secondary ranges in the subnetwork to enable IP aliases, one for the pod IPs and another to reserve space for the services range ([source](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--enable-ip-alias)).

Looking at this [guide](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#custom_subnet), it looks like you don't necessarily need to specify `ipAllocationPolicy.clusterIpv4CidrBlock` and `ipAllocationPolicy.servicesIpv4CidrBlock`, though it looks like you need to specify `ipAllocationPolicy.clusterSecondaryRangeName` and `ipAllocationPolicy.servicesSecondaryRangeName`. Can you try specifying those fields and see if that works?

**Comment by Synehan** [comment]
Hi @jcanseco, thanks for the answer.

I've looked at all the version we deployed of config connector and `ipAllocationPolicy.useIpAliases` was present and working with the version 1.0 (image tag `20b8c72` and label `controller-tools.k8s.io: "1.0"`).

I will try with `ipAllocationPolicy.clusterSecondaryRangeName` and `ipAllocationPolicy.servicesSecondaryRangeName` but I think i will need to create thoses secondary subnet by myself (or through Config Config ;)) through this method.

I'll keep you updated

**Comment by jcanseco** [comment]
Hi @Synehan, ah I stand corrected! I must've missed that during my investigation. The image tag `20b8c72` is from KCC version 0.3.7; the label `controller-tools.k8s.io` refers to something else. Yes, you will have to create those secondary ranges on your subnetwork yourself. Please let me know if you encounter any issues.

**Comment by itaimalek** [comment]
@jcanseco - Hi there
I came across this thread as we are experiencing a similar problem with config-connector trying to create a containerCluster.
we took your advice on creating the secondary ip ranges for both pods and services but still getting the same error.

we are deploying this:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    env: dev
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: itai-control
spec:
  minMasterVersion: 1.15.12-gke.2
  location: europe-west1-c
  initialNodeCount: 1
  networkPolicy:
    enabled: true
  resourceUsageExportConfig:
    enableResourceConsumptionMetering: true
    enableNetworkEgressMetering: true
    bigqueryDestination:
      datasetId: control
  ipAllocationPolicy:
    clusterSecondaryRangeName: "gke-itai-control-pods-1"
    servicesSecondaryRangeName: "gke-itai-control-svcs-1"
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: "172.16.10.0/28"
  masterAuthorizedNetworksConfig:
    cidrBlocks: []
```

and getting this error:
`message: 'Update call failed: error validating configuration: "ip_allocation_policy":
      conflicts with cluster_ipv4_cidr'`

this is the full object:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: resource
    cnrm.cloud.google.com/project-id: elementor-hosting
    cnrm.cloud.google.com/remove-default-node-pool: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"container.cnrm.cloud.google.com/v1beta1","kind":"ContainerCluster","metadata":{"annotations":{"cnrm.cloud.google.com/remove-default-node-pool":"true"},"labels":{"env":"dev"},"name":"itai-control","namespace":"default"},"spec":{"initialNodeCount":1,"ipAllocationPolicy":{"clusterSecondaryRangeName":"gke-itai-control-pods-1","servicesSecondaryRangeName":"gke-itai-control-svcs-1"},"location":"europe-west1-c","masterAuthorizedNetworksConfig":{"cidrBlocks":[]},"minMasterVersion":"1.15.12-gke.2","networkPolicy":{"enabled":true},"privateClusterConfig":{"enablePrivateEndpoint":false,"enablePrivateNodes":true,"masterIpv4CidrBlock":"172.16.10.0/28"},"resourceUsageExportConfig":{"bigqueryDestination":{"datasetId":"control"},"enableNetworkEgressMetering":true,"enableResourceConsumptionMetering":true}}}
  creationTimestamp: "2020-07-07T09:05:43Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 25
  labels:
    env: dev
  name: itai-control
  namespace: default
  resourceVersion: "338563"
  selfLink: /apis/container.cnrm.cloud.google.com/v1beta1/namespaces/default/containerclusters/itai-control
  uid: f10c5f7d-e929-4a06-934f-0e8fa3a04add
spec:
  addonsConfig:
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: false
  clusterIpv4Cidr: 10.120.0.0/14
  databaseEncryption:
    state: DECRYPTED
  defaultMaxPodsPerNode: 110
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterIpv4CidrBlock: 10.120.0.0/14
    clusterSecondaryRangeName: gke-itai-control-pods-1
    servicesIpv4CidrBlock: 10.110.0.0/20
    servicesSecondaryRangeName: gke-itai-control-svcs-1
  location: europe-west1-c
  loggingService: logging.googleapis.com/kubernetes
  masterAuth:
    clientCertificateConfig:
      issueClientCertificate: false
    clusterCaCertificate: LS0t...
  minMasterVersion: 1.15.12-gke.2
  monitoringService: monitoring.googleapis.com/kubernetes
  networkPolicy:
    enabled: true
  networkRef:
    external: projects/elementor-hosting/global/networks/default
  nodeVersion: 1.15.12-gke.2
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.10.0/28
    peeringName: gke-n1d019e5f9e079568c74-ae32-e7a3-peer
    privateEndpoint: 172.16.10.2
    publicEndpoint: 35.187.63.228
  releaseChannel:
    channel: UNSPECIFIED
  resourceUsageExportConfig:
    bigqueryDestination:
      datasetId: control
    enableNetworkEgressMetering: true
    enableResourceConsumptionMetering: true
  subnetworkRef:
    external: projects/elementor-hosting/regions/europe-west1/subnetworks/default
status:
  conditions:
  - lastTransitionTime: "2020-07-07T09:12:10Z"
    message: 'Update call failed: error validating configuration: "ip_allocation_policy":
      conflicts with cluster_ipv4_cidr'
    reason: UpdateFailed
    status: "False"
    type: Ready
  endpoint: 35.187.63.228
  labelFingerprint: 38f168e5
  masterVersion: 1.15.12-gke.2
  servicesIpv4Cidr: 10.110.0.0/20
```


it seems that there is a config conflict as `ip_allocation_policy` and `cluster_ipv4_cidr` cannot live side by side, and for some reason the API thinks there is a default value for `cluster_ipv4_cidr` even though we are not sending it at all.

**Comment by Synehan** [comment]
I've managed to deploy a GKE cluster with ip_allocation_policy with theses values:

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
    cnrm.cloud.google.com/project-id: "XXXXXXXXXXXX"
  labels:
    cluster: mycluster
  name: mycluster
spec:
  addonsConfig:
    cloudrunConfig:
      disabled: true
    horizontalPodAutoscaling:
      disabled: true
    httpLoadBalancing:
      disabled: false
    istioConfig:
      disabled: false
      auth: AUTH_MUTUAL_TLS
    networkPolicyConfig:
      disabled: false
  description: "GKE Cluster XXXXXX"
  enableIntranodeVisibility: false
  enableKubernetesAlpha: false
  enableShieldedNodes: false
  enableTpu: false
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterIpv4CidrBlock: 10.128.0.0/14
    servicesIpv4CidrBlock: 10.132.0.0/20
  location: europe-west1
  loggingService: logging.googleapis.com/kubernetes
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "01:00"
  minMasterVersion: 1.16.8-gke.15
  monitoringService: monitoring.googleapis.com/kubernetes
  networkPolicy:
    enabled: true
    provider: CALICO
  networkRef:
    name: continuous-testing
  podSecurityPolicyConfig:
    enabled: false
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.2.0/28
  releaseChannel:
    channel: REGULAR
  subnetworkRef:
    name: mysubnet
  verticalPodAutoscaling:
    enabled: false
  workloadIdentityConfig:
    identityNamespace: XXXXX.svc.id.goog
```

KCC version: 1.12.1

**Comment by itaimalek** [comment]
@Synehan - hey, thanks for your reply.
If I understand correctly you are using Config-Connector v1.12.1 ?
 my config connector is 1.13.1 and I think they have an issue there.

How did you manage to determine the specific Config-Connector version for your controller?

**Comment by Synehan** [comment]
@itaimalek there is usually an annotation on the cnrm pods and ressources `cnrm.cloud.google.com/version:`
The container version of our deployment is : `4925e84`

**Comment by itaimalek** [comment]
@Synehan  Thanks for the docker image tag, it really was a bet which one to choose.
it seems to work as expected now.
seems like a real defect on v1.13.1 though.

**Comment by jcanseco** [comment]
Hi @itaimalek, thanks for reporting this. I was able to reproduce the error you saw:

```
'Update call failed: error validating configuration: "ip_allocation_policy": conflicts with cluster_ipv4_cidr'
```

If I'm understanding the issue correctly, you were able to create the `ContainerCluster` successfully in that it managed to reach an `UpToDate` state, but it later transitioned to `UpdateFailed` in subsequent reconciliations. Can you confirm that this is what you observed?

I believe this is an issue with the resource validation logic we recently added in v1.13.1. We'll look into it as a bug and let you know when we have further updates.

**Comment by itaimalek** [comment]
@jcanseco - yes, that exactly right, the cluster is being provisioned, but in the next reconciliation it fails to update.
in v1.12.1 everything worked as expected.

small request until we have a fix for v1.13.1 - please document the docker tag we need to use in order to work with v1.12.1

**Comment by jcanseco** [comment]
@itaimalek thanks for confirming. v1.12.1 uses `4925e84`.

**Comment by jcanseco** [comment]
@itaimalek thanks for confirming. The docker tag used by v1.12.1 is `4925e84`. 

It seems your intention is to do a downgrade though? Our current official recommendation for downgrades is to do a complete uninstall and reinstall of KCC. Note that this will cause KCC to abandon all your existing resources, which may not be an option for you, and so the motivation to consider an in-place downgrade which I believe is what you're looking to do.

In-place downgrades are, however, not yet something we currently support or test, and it may instead actually cause you problems instead of helping especially if there were CRD schema changes between the versions.

If you must do an in-place downgrade, we recommend downgrading to v1.13.0 instead, since there seems to be no real CRD schema changes between v1.13.0 and v1.13.1, and v1.13.0 does not contain the validation logic added in v1.13.1 that is causing your issues.

You should be able to perform an in-place downgrade by following our [upgrade steps](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#manual-upgrade) Note: once you get to the "manual install steps", you should download and install `gs://cnrm/1.13.0/release-bundle.tar.gz` instead of the latest.

**Comment by jcanseco** [comment]
Hi @itaimalek, we just released v1.15.0 which should have fixed the issue. [Another user who faced the same problem confirmed that the fixed work](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/242#issuecomment-659628286), so I'll be closing this issue now, but please feel free to re-open if you have any further issues!
